<h3 class="text-center" >Connectez vous !</h3>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<?php echo $this->form()->openTag($form) ?>

    <dl class="zend-form form-horizontal">
        <?php echo $this->formElementErrors($form->get('identity')) ?>
        <dd>
            <div class="form-group">
                <label class="control-label col-sm-2 col-md-4"><?php echo $this->formLabel($form->get('identity')) ?></label>
                <div class="col-sm-6 col-md-8">
                    <?php $form->get('identity')->setAttribute('class','form-control')?>
                    <?php echo $this->formInput($form->get('identity')) ?>
                </div>
            </div>
                    
        </dd>
        <dd>
            <div class="form-group">
                <label class="control-label col-sm-2 col-md-4"><?php echo $this->formLabel($form->get('credential')) ?></label>
                <div class="col-sm-6 col-md-8">
                    <?php $form->get('credential')->setAttribute('class','form-control')?>
                    <?php echo $this->formInput($form->get('credential')) ?>
                </div>
            </div>
                    
        </dd>
        <?php if ($this->redirect): ?>
            <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
        <?php endif ?>

        <?php $form->get('submit')->setAttribute('class','btn btn-info') ?>
        <dd><?php echo $this->formButton($form->get('submit')) ?></dd>
        
    </dl>

<?php echo $this->form()->closeTag() ?>

<?php if ($this->enableRegistration) : ?>
Not registered? <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Sign up!</a>
<?php endif; ?>
