<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Apiculture'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/Favicon.png'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
      <div id="content" class="col-lg-12 col-sm-12 col-xs-12">

        <header>



            <nav id="navbar" class="navbar" role="navigation">
                <h1>Apiculture application</h1>
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar_menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="visible-xs">Menu</span>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar_menu">
      <ul class="nav navbar-nav">
        <li><a href="<?php echo $this->url('home')?>">Accueil</a></li>
        <li><a <?php if(!$this->zfcUserIdentity()) echo 'class=access_denied data-toggle=tooltip data-placement=top title=Connectez-vous href=#'; else echo 'href='.$this->url('home');?>>Mon compte</a></li>
        <li><a <?php if(!$this->zfcUserIdentity()) echo 'class=access_denied data-toggle=tooltip data-placement=top title=Connectez-vous href=#'; else echo 'href='.$this->url('dashboard');?>>Dashboard</a></li>
        <li class="right">Pas encore inscrit ?
            <a href="<?php echo $this->url('zfcuser/register'); ?>"><?php echo $this->translate('Register') ?>
            </a>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

        </header>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
            <!--<hr>-->
            <footer>
                <!--<p>&copy; 2005 - <?php date_default_timezone_set('Europe/Paris'); echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>-->
            </footer>
               <?php echo $this->inlineScript() ?>


</div>
</body>
</html>

