<h1>Ajout d'une rûche ! </h1>
<?php
    $form = $this->form;
    $form->setAttribute('action', $this->url('add', array('action' => 'addhive')));
    $form->prepare();
    echo $this->form()->openTag($form);
?>

<table class="zend_form">
    <tr>
        <td>
            <?php echo $this->formRow($form->get('name'));?>
        </td>
    </tr>
    
    <!--<tr>
        <td><?php echo $this->formLabel($form->get('latitude')); ?></td>
        <td><?php echo $this->formInput($form->get('latitude'));
            echo $this->formElementErrors($form->get('latitude'));?></td>
    </tr>-->
            
    <tr>
        <td>
            <?php echo $this->formRow($form->get('longitude')); ?>
        </td>
    </tr>
    
        <tr>
        <td>
            <?php echo $this->formRow($form->get('latitude')); ?>
        </td>
    </tr>
    
    <tr>
        <td>
            <?php echo $this->formRow($form->get('submit')); ?>
        </td>
    </tr>
</table>

<?php echo $this->form()->closeTag($form); ?>
