<?php include_once 'addhive.phtml'; ?>
<?php include_once 'intervention.phtml'; ?>
<?php include_once 'addintervention.phtml'; ?>
<?php include_once 'production.phtml'; ?>
<?php include_once 'addproduction.phtml'; ?>

<?php $username = substr($this->zfcUserIdentity()->getEmail(),0,strpos($this->zfcUserIdentity()->getEmail(),'@')); ?>
<h3 class="dashboard_title">Bienvenue <?php echo $username ?></h3>
<?php if (sizeof($hives) > 0) { ?>
    <div id="list-hives" class="col-sm-2 col-xs-12">
        <h4>Liste de vos rûches</h4>
        <ul>
            <?php
            for ($i=0;$i<sizeof($hives);$i++) {
                if ($i == sizeof($hives)-1) echo '<div class="content_hive_list last">'; else echo '<div class="content_hive_list">';
                echo "<li id=".$hives[$i]->getId().">".$hives[$i]->getName()."</li>";?>
                <a class="idHiveDelete" title="Supprimer" href="<?php echo $this->url('delete',array('action'=>'deletehive', 'id'=>$hives[$i]->getId()))?>">
                    <span id="<?php echo $hives[$i]->getId(); ?>" class="glyphicon glyphicon-remove-circle idHiveDelete" data-toggle="modal" data-target="#myModalDelete"></span>
                </a>
                <a class="idHiveUpdate" title="Modifier" href="<?php echo $this->url('update',array('action'=>'updatehive', 'id'=>$hives[$i]->getId()))?>">
                    <span id="<?php echo $hives[$i]->getId(); ?>" class="glyphicon glyphicon-pencil idHiveDelete" data-toggle="modal" data-target="#myModalUpdate"></span>
                </a></div>


            <?php }?>
        </ul>
    </div>
<?php } ?>
<div id="map" class="col-sm-8 col-xs-12<?php if (sizeof($hives) == 0) echo ' col-sm-offset-1'?>">
    <?php echo $mapHelper->render($map); ?>
</div>
<div class="btn_add_hive col-sm-2"><button class="btn btn-info" data-toggle="modal" data-target="#modalAdd">Ajouter une ruche</button></div>
<div class="hidden content_javascript_hive col-sm-2"></div>
<div class="modal fade" id="myModalDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Supprimer une rûche</h4>
      </div>
      <div class="modal-body">
        <p>Voulez-vous vraiment supprimer cette rûche ?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a id="idHiveDelete" href="">Supprimer</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="myModalUpdate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Modifier une rûche</h4>
      </div>
      <div class="modal-body">
        <?php
            /*$form = $this->form;
            $form->setAttribute('action', $this->url('update', array('action' => 'updatehive')));
            $form->prepare();
            echo $this->form()->openTag($form);
            var_dump($form);*/
        ?>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a id="idHiveUpdate" href="">Modifier</a>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script>
    $('.idHiveDelete').click(function()
    {
        $('#idHiveDelete').attr('href',$(this).attr('href'));
    });

    $('.idHiveUpdate').click(function()
    {
        $('#idHiveUpdate').attr('href',$(this).attr('href'));
    });

    $('#map').click(function()
    {
       jQuery.globalEval($('#javascript_content').html());
       $('.content_javascript_hive').html($('#content_infoWindow').html());
    });

</script>
