<div class="modal fade" id="modalIntervention" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Liste des interventions</h4>
            </div>
            <div class="modal-body">
                <span id="url_intervention" class="hidden"><?php echo $this->url('intervention'); ?></span>
                    <span id="url_display_pagination" class="hidden"><?php echo $this->url('displaypagination'); ?></span>
                <ul class="list_interventions">

                </ul>
                <ul class="pages">

                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info production_hive" data-toggle="modal" data-target="#modalProduction">Production</button>
                <button id="addIdHiveToIntervention" type="button" class="btn btn-info" data-toggle="modal" data-target="#modalAddIntervention">Ajouter une intervention</button>
                <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $('#modalIntervention').on('show.bs.modal', function()
        {
            displayPagination();
            $('.list_interventions').empty();
            $.ajax({
                url : $('#url_intervention').html(),
                type : 'POST',
                dataType  :'json',
                data : {
                    id_hive : $('.hive_name').attr('id'),
                }

            }).success(function(response){
                if (response.length != 0) {
                    for (var intervention in response) {
                        $('.list_interventions').append('<li class="border">'+response[intervention]['description']+ ' le ' + response[intervention]['date']+'</li>');
                    }
                } else $('.list_interventions').append('<li>Il n\'y a pas d\'interventions sur cette ruche</li>');
            });
        });



        function displayPagination()
        {
            $.ajax({
                url : $('#url_display_pagination').html(),
                type : 'POST',
                dataType  :'json',
                data : {
                    id_hive : $('.hive_name').attr('id'),
                }

            }).success(function(response){
                if (response.length != 0) {
                    var nb_pages = response[1];
                    nb_pages = Math.ceil(nb_pages/10);
                    console.log(nb_pages);
                    for (var i=1;i<=nb_pages;i++) {
                        $('.pages').append('<li class=pagination id='+i+'>'+ i + '</li>');
                    }
                }
                $('.pagination').click(function()
                {
                    $('.list_interventions').empty();
                    var npage = $(this).attr('id');
                    $.ajax({
                        url : $('#url_intervention').html(),
                        type : 'POST',
                        dataType : 'json',
                        data : {
                            id_hive : $('.hive_name').attr('id'),
                            page : npage
                        }
                    }).success(function(datas){
                        if (datas.length != 0) {
                            for (var intervention in datas) {
                                $('.list_interventions').append('<li class="border">'+datas[intervention]['description']+ ' le ' + datas[intervention]['date']+'</li>');
                            }
                        } else $('.list_interventions').append('<li>Il n\'y a pas d\'interventions sur cette ruche</li>');
                    });
                });
            });
        };


        $('#addIdHiveToIntervention').click(function()
        {
            $('input[name=id_hive]').attr('value',$('.hive_name').attr('id'));
        });


    });



</script>


