<div class="modal fade" id="modalIntervention" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Liste des interventions</h4>
            </div>
            <div class="modal-body">
                <span id="url_intervention" class="hidden"><?php echo $this->url('intervention'); ?></span>
            <ul class="list_interventions">

            </ul>
            <div><a class="pagination" id="1" href="#">1</a>&nbsp;<a class="pagination" id="2" href="#">2</a>&nbsp;<a class="pagination" id="3" href="#">3</a>&nbsp;<a class="pagination" id="4" href="#">4</a></div>
            </div>
            <div class="modal-footer">
                <button id="addIdHiveToIntervention" type="button" class="btn btn-info" data-toggle="modal" data-target="#modalAddIntervention">Ajouter une intervention</button>
                <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script>
    $('#modalIntervention').on('show.bs.modal', function()
    {
        $('.list_interventions').empty();
        $.ajax({
            url : $('#url_intervention').html(),
            type : 'POST',
            dataType  :'json',
            data : {
                id_hive : $('.hive_name').attr('id'),
            }

        }).success(function(response){
            console.log('succes');
            console.log(response);
            if (response.length != 0) {
                for (var intervention in response) {
                    $('.list_interventions').append('<li class="border">'+response[intervention]['description']+ ' le ' + response[intervention]['date']+'</li>');
                }
            } else $('.list_interventions').append('<li>Il n\'y a pas d\'interventions sur cette ruche</li>');
        });
    });

    $('.pagination').click(function()
    {
        $('.list_interventions').empty();
        var npage = $(this).attr('id');
        console.log(npage);
        $.ajax({
            url : $('#url_intervention').html(),
            type : 'POST',
            dataType : 'json',
            data : {
                id_hive : $('.hive_name').attr('id'),
                page : npage
            }
        }).success(function(datas){
            if (datas.length != 0) {
                for (var intervention in datas) {
                    $('.list_interventions').append('<li class="border">'+datas[intervention]['description']+ ' le ' + datas[intervention]['date']+'</li>');
                }
            } else $('.list_interventions').append('<li>Il n\'y a pas d\'interventions sur cette ruche</li>');
        });
    });


    $('#addIdHiveToIntervention').click(function()
    {
        $('input[name=id_hive]').attr('value',$('.hive_name').attr('id'));
    });
</script>


