<div class="modal fade" id="modalProduction" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Liste des interventions</h4>
            </div>
            <div class="modal-body">
                <span id="url_production" class="hidden"><?php echo $this->url('production'); ?></span>
                <div id="chart_div"></div>


            </div>
            <div class="modal-footer">
                <button id="addProduction" type="button" class="btn btn-info">Production</button>
                <button id="addIdHiveToIntervention" type="button" class="btn btn-info" data-toggle="modal" data-target="#modalAddIntervention">Ajouter une intervention</button>
                <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script>
    /*google.load('visualization', '1.0', {'packages':['corechart']});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('date', 'Mois');
        data.addColumn('number', 'Production (g)');
        $.ajax({
            url : $('#url_production').html(),
            type : 'POST',
            dataType  :'json',
            data : {
                id_hive : $('.hive_name').attr('id'),
            }
        }).success(function(response){
            if (response.length != 0) {
                for (var production in response) {
                    data.addRows([
                        [new Date(response[production]['date']), response[production]['production']]}],
                }
            } else $('.list_interventions').append('<li>Il n\'y a pas d\'interventions sur cette ruche</li>');
        });

        var options = {'title':'Production',
            'width':600,
            'height':300};

        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }*/
        google.load('visualization', '1', {'packages':['corechart']});
        google.setOnLoadCallback(initialize);
        function drawChart() {
            var jsonData = $.ajax({
                url: $('#url_production').html(),
                type : 'POST',
                dataType:'json',
                data : {
                    id_hive : $('.hive_name').attr('id')
                },
                async: false
            }).responseText;
            console.log(jsonData);
            /*var courses = {
                "fruits": [
                    { "kiwis": 3,
                        "mangues": 4,
                        "pommes": null
                    },
                    { "panier": true },
                ],
                "legumes":
                { "patates": "amandine",
                    "figues": "de barbarie",
                    "poireaux": false
                }
            };*/

        var data = new google.visualization.DataTable(jsonData);
        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, {width: 400, height: 240});
        }

    function initialize () {
        $('.production_hive').click(function() {
            drawChart();
        });
    }







</script>
