<div class="modal fade" id="modalProduction" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Liste des interventions</h4>
            </div>
            <div class="modal-body">
                <div id="chart_div"></div>


            </div>
            <div class="modal-footer">
                <button id="addProduction" type="button" class="btn btn-info">Production</button>
                <button id="addIdHiveToIntervention" type="button" class="btn btn-info" data-toggle="modal" data-target="#modalAddIntervention">Ajouter une intervention</button>
                <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script>
    google.load('visualization', '1.0', {'packages':['corechart']});
    google.setOnLoadCallback(drawChart);
    function drawChart() {
        var data = new google.visualization.DataTable();
        data.addColumn('date', 'Mois');
        data.addColumn('number', 'Production (g)');
        data.addRows([[new Date(2008,3,0), 3]]);
        data.addRows([[new Date(2010,11,8), 10]]);
        var options = {'title':'Production',
            'width':600,
            'height':300};

        var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
        chart.draw(data, options);
    }



    </script>
