<div class="modal fade" id="modalProduction" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Production de la ruche</h4>
            </div>
            <div class="modal-body">
                <span id="url_production" class="hidden"><?php echo $this->url('production'); ?></span>
                <div id="chart_div"></div>


            </div>
            <div class="modal-footer">
                <button id="addIdHiveToProduction" type="button" class="btn btn-info" data-toggle="modal" data-target="#modalAddProduction">Ajouter une récolte</button>
                <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script>
        google.load('visualization', '1', {'packages':['corechart']});
        google.setOnLoadCallback(initialize);
        function drawChart() {
            var jsonData = $.ajax({
                url: $('#url_production').html(),
                type : 'POST',
                dataType:'json',
                data : {
                    id_hive : $('.hive_name').attr('id')
                },
                async: false
            }).responseText;

            var data = new google.visualization.DataTable(jsonData);
            var chart = new google.visualization.LineChart(document.getElementById('chart_div'));
            chart.draw(data, {width: 540, height: 300});
            var data = $.parseJSON(jsonData);
            $('#chart_div').append('<p style="text-align:center">La production totale de cette rûche est de '+data.poids+' grammes.');
        }

    function initialize () {
        $('.production_hive').click(function() {
            drawChart();
        });

        $('#addIdHiveToProduction').click(function()
        {
            $('input[name=id_hive]').attr('value',$('.hive_name').attr('id'));
        });
    }
</script>
