<div id="main" class="thumbnail col-lg-12 col-md-12 col-xs-12">
    <div id="login" class="jumbotron col-lg-6 col-md-6 col-xs-12">
        <?php echo $this->zfcUserLoginWidget(); ?>
    </div>

    <div id="info" class="col-lg-6 col-md-6 col-xs-12">
        <h2 class="text-center">Gère tes ruches !</h2>
        <p class="text-center">Bienvenue sur le site d'apiculture. En te créant un compte tu auras accès à ton espace personnel dans lequel tu pourras gérer tes ruches, tes récoltes...</p>
        <div class="row text-center">
            <img class="" src="../../../../img/miel.png" alt="Miel" height="200" width="150">
        </div>
    </div>
</div>
