<div class="contenu row thumbnail col-sm-6 col-md-12">
    <div class="jumbotron col-sm-4 col-md-6">
        <?php echo $this->zfcUserLoginWidget(); ?>
    </div>
    
    <div class="col-md-6">
        <h2 class="text-center">Gère tes ruches !</h2>
        <p class="text-center">Bienvenue sur le site d'apiculture. Ici, tu peux gérer tes ruches et tes récoltes.<br/> Si tu n'as pas encore de compte inscris toi !</p>
        <div class="row text-center">
            <img class="" src="../../../../img/miel.png" alt="Miel" height="200" width="150"> 
        </div>
    </div>
</div>







        